### ISSUE TITLE
Server: player state

### ISSUE THREAD

**Issue by TheCatPlusPlus** [LoungeCPP/Tatsoryk#10]
Server should be able to:
- [x] assign an ID to a connecting player
- [x] spawn an entity for a player
- [x] despawn a player entity
- [x] despawn player and their bullets when they disconnect
- [x] track current position and movement vector of the player entity
- [x] reject movement updates that would result in crossing of the map boundary
- [x] reject movement updates that would result in players overlapping
- [x] send a stop_movement message when players are forced to stop
- [x] broadcast network updates on player state changes

**Comment by nabijaczleweli** [comment]
Don't think "_despawn player_ **_and their bullets**_ _when they disconnect_" should be a thing. If I die, the bullets I shot are still very much alive and coming for you.

**Comment by TheCatPlusPlus** [comment]
Maybe but that complicates killer tracking. I'd say despawn everything for now.

**Comment by EthanSteinberg** [comment]
I'll look into whatever is preventing players from being removed when they leave now.
