### ISSUE TITLE
Design: initial application protocol

### ISSUE THREAD

**Issue by TheCatPlusPlus** [LoungeCPP/Tatsoryk#2]
See https://github.com/LoungeCPP/Tatsoryk/wiki/Protocol-spec for current version.

Version/feature negotiation can be added in the future if needed. Client and server is assumed to be always talking the same iteration of the protocol, and the behaviour is undefined otherwise.

I'm ignoring differences in viewport sizes, in future this should be addressed somehow so players with bigger screens don't get an advantage.

I didn't include aiming updates, we can probably live without rendering other players' aim vectors.

**Comment by thecoshman** [comment]
I don't see why the `welcome` message carries this players `speed` and `bullet_speed`, seems maybe a bit pointless to me. It should also send the new player information about all other players, a collection of player IDs, where they are etc.

Like with the `welcome` message, not sure why `player_joined` sends `speed` and `bullet_speed`.

`shots_fired` should either be renamed to `shot_fired` or actually send information about all shots, though that would require the server track what bullets it has told clients about. Though if each bullet is it's own id, the server can just send all 'in flight' bullets. The message should also send the bullet speed, so that client can animate it.

If the `entity_spawned` and `entity_destroyed` are specifically for the player, they should be named such. What about other sorts of entities, like the exploding barrel trope?

`world_state` probably should include all entities, including bullets. It will allow the client to ensure it is correct, that it never missed any updates. 

`start_moving` and `stop_moving`... how do these handle if the player holds many keys down? Do they just keep sending `start_moving` messages and the server just takes the latest? Do we also want to allow the client to send where it thinks it currently is? This could allow the server and client to smooth out disagreements.

**Comment by nabijaczleweli** [comment]
How should optional arguments be serialized, @TheCatPlusPlus?

**Comment by TheCatPlusPlus** [comment]
> I don't see why the welcome message carries this players speed and bullet_speed, seems maybe a bit pointless to me.

Well, I mentioned that at the start, to not have to change that in two places (because the values must be in sync between client and server).

>  It should also send the new player information about all other players, a collection of player IDs, where they are etc.

Maybe, but we might as well just send full update message right afterwards.

> shots_fired should either be renamed to shot_fired or actually send information about all shots

itsajoke

> The message should also send the bullet speed, so that client can animate it.

I assume it'll be constant throughout, that's why it's sent only once when player joins. A better system can be done in future.

> Do they just keep sending start_moving messages and the server just takes the latest?

Yeah, just send an update with a new vector.

> world_state probably should include all entities, including bullets.

Actually yeah, probably, because while bullets can be perfectly predicted a newly joining player will need to see all the existing ones.

> If the entity_spawned and entity_destroyed are specifically for the player, they should be named such. What about other sorts of entities, like the exploding barrel trope?

Eh, bikeshed. Can be player_X.

> How should optional arguments be serialized, @TheCatPlusPlus?

I think just omit them, don't remember what Rust serialisers do.

**Comment by nabijaczleweli** [comment]
Alright, apparently JS `JSON.serialize()` also omits them.

**Comment by TheCatPlusPlus** [comment]
Renamed entity_X to player_X, added a requirement for optionals.

**Comment by TheCatPlusPlus** [comment]
Also added bullet data and movement vectors to the full state update.

**Comment by TheCatPlusPlus** [comment]
Do we want simultaneous bullet limits/fire cooldown in the MVP? It'll probably be Fun otherwise, but I guess we could live with that.

**Comment by thecoshman** [comment]
Ergh... initially maybe just let the bullet spam happen, compensate with slow bullets. Wouldn't be much work after that to do cool down.

**Comment by andyprowl** [comment]
The text description of the `world_state` message says "bullets not included", but the bullets below it (no pun intended) include it. I guess the sentence was there prior to Pirate's suggestion and can now be removed.

**Comment by TheCatPlusPlus** [comment]
Yes, also I guess there should be data constants for sizes of bullets and ships too, if we're going that way. Or should we just drop that and hardcode in two places?

**Comment by TheCatPlusPlus** [comment]
I moved it to wiki so there's history (because why would anyone want history of the issue or even a note that it was edited right GitHub???).

Also:
- clarified that the vectors are directions and don't represent velocities
- removed the thing Andy mentioned
- clarified 'player entity' to 'player vehicle' to avoid confusion
- removed data fields from `player_joined` message — they won't change from player to player so they can all be included in `welcome`
- added vehicle and bullet size to `welcome` in the same vein as speeds
- renamed `fire_speed` to `bullet_speed` to clarify its purpose
- specified explicitly that distance units are pixels and time units are seconds
- specified explicitly that vehicles are squares and bullets are circles
- specified explicitly that non-typechecking messages are malformed

**Comment by TheCatPlusPlus** [comment]
NB timeDelta in the client stub is milliseconds.

**Comment by thecoshman** [comment]
If there is a wiki for this, link to and close this?

**Comment by TheCatPlusPlus** [comment]
No, this is tracking issue, we'll close it after everything's finalised.

I've relaxed malformed message definition to make ignoring extra fields valid behaviour too (doesn't require changes if the stuff already rejects these, though).

**Comment by thecoshman** [comment]
Ah, we can't discuss on this wiki can we, yay for features!

**Comment by thecoshman** [comment]
SHOULD clients send a go_away message if they are intending to quite? Or are we just going to fall back on handling it when the socket collapses?

**Comment by TheCatPlusPlus** [comment]
No, clients just close the socket, go_away is just an optional server->client notification.

**Comment by nabijaczleweli** [comment]
Is this closeable now? It's implemented on both sides.

**Comment by thecoshman** [comment]
I think so... There's improvements to be made to the handling, but I think they are implemented. Plus, we are of course going to modify these over time as need be, and it'll stupid to hold this open forever.
