### ISSUE TITLE
Support TLS

### ISSUE THREAD

**Issue by nabijaczleweli** [LoungeCPP/Tatsoryk#55]
Ability to connect via `wss://`
- [ ] server: use specified `.pem`s
- [ ] client: verify ability to use `wss://` instead of `ws://`

**Comment by TheCatPlusPlus** [comment]
nginx can act as a TLS terminator, and browsers implement everything already so there's really nothing to do here.

**Comment by nabijaczleweli** [comment]
I was thinking of doing [this](http://cyderize.github.io/rust-websocket/doc/websocket/server/struct.Server.html#secure-servers), but whatever you say, you're the sysadmin here

**Comment by TheCatPlusPlus** [comment]
Don't touch TLS if you don't have to. :v

**Comment by nabijaczleweli** [comment]
very well
