### ISSUE TITLE
Clients kill themselves w/ own bullets

### ISSUE THREAD

**Issue by nabijaczleweli** [LoungeCPP/Tatsoryk#57]
Probably incorrect offsetting on the client

Tops off and closes #58

**Comment by nabijaczleweli** [comment]
Looks like it's because the player already starts to move before `fire` and `shots_fired` cycle, immediately hitting the player on its new position.
This is purely a network problem, however it can be fixed by just not letting players be killed by own bullets.

**Comment by EthanSteinberg** [comment]
Make the players unkillable by their own bullets.
