### ISSUE TITLE
Client: player input

### ISSUE THREAD

**Issue by TheCatPlusPlus** [LoungeCPP/Tatsoryk#6]
Client should be able to:
- [x] track WASD state and adjust player movement vector accordingly (and send network updates)
- [x] track mouse position and adjust aiming vector accordingly
- [x] track left mouse button state and spawn bullets accordingly (and send network updates)

**Comment by nabijaczleweli** [comment]
Dual-stick controller support?

**Comment by thecoshman** [comment]
Not for the MVP

**Comment by EthanSteinberg** [comment]
#25
